/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    AlbiteTable: {
      name: string;
      type: 'sst.aws.Dynamo';
    };
    AlbiteTrpc: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
    AlbiteWeb: {
      type: 'sst.aws.SvelteKit';
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
