/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
	export interface Resource {
		PlagioClaseTable: {
			name: string;
			type: 'sst.aws.Dynamo';
		};
		PlagioClaseTrpc: {
			name: string;
			type: 'sst.aws.Function';
			url: string;
		};
		PlagioClaseWeb: {
			type: 'sst.aws.SvelteKit';
		};
	}
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
